### ISSUE TITLE
Password input on OS X

### ISSUE THREAD

**Issue by jmakeig** [arekinath/node-getpass#1]
The OS X terminal has some special provisions for entering passwords. According to [Stack Overflow](http://superuser.com/a/1014123), “Terminal enters this mode when it sees that the TTY device is configured for canonical (aka ‘cooked’) mode and character echo is off”. It would be nice if getpass were able to trigger this.

**Comment by arekinath** [comment]
Sadly all that node.js gives us for this is the `setRawMode()` call on ttys -- which calls `uv_tty_set_mode` from `libuv`. You can see exactly what it does here: https://github.com/libuv/libuv/blob/v1.x/src/unix/tty.c#L216 -- and also see that there is no way to make it turn off `ECHO` without also turning off `ICANON` (canonical mode).

You could happily do this in a C extension yourself, but then you have to fight the endless wars of node C API/ABI instability and version breakage. One of the reasons I made this module was to do it in pure Javascript without dealing with that.

So... I'm sorry, but I don't think it's going to happen. Maybe we could make a C extension as an `optionalDependency` of this module -- like the way that `bunyan` does `dtrace-provider` -- so that if it fails to build it falls back to the pure JS code... but that's been pretty flakey lately, too (npm doesn't seem to care very much about testing `optionalDependencies` build failures)

**Comment by jmakeig** [comment]
Thanks for the thorough response. None of your suggestions sounds worth it, as you'd already concluded.
